config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'decline', to: 'bookings#decline_booking', as: :decline
  get 'accept', to: 'bookings#accept_booking', as: :accept
  get 'my_garages', to: 'garages#my_garages', as: :my_garages
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :garages do
    resources :bookings, only: %i[new create]
  end
  resources :bookings, only: %i[index edit update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :client, class_name: "User", foreign_key: "client_id"
  belongs_to :garage
  has_many :reviews

  scope :confirmed, -> { where(status: "confirmed") }

  def confirmed?
    status == 'confirmed'
  end
end

app/models/garage.rb
class Garage < ApplicationRecord
  belongs_to :owner, class_name: "User", foreign_key: "owner_id"
  has_many :bookings, dependent: :destroy #asi si borro garage que tiene booking, me deja borrarlo.

  has_one_attached :photo

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  include PgSearch::Model
  pg_search_scope :search_by_title_and_description,
    against: [ :title, :location ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :garages, foreign_key: 'owner_id', dependent: :destroy
  has_many :bookings, foreign_key: 'client_id', dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:full_name])
  end

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: %i[index my_garages], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: %i[index my_garages], unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :set_booking, only: %i[edit update destroy decline_booking accept_booking]

  def index
    @bookings_owner = policy_scope(Booking).select do |booking|
      booking.garage.owner == current_user
    end

    @bookings_client = policy_scope(Booking).select do |booking|
      booking.client == current_user
    end
  end

  def new
    @booking = Booking.new
    @garage = Garage.find(params[:garage_id])
    authorize @booking
  end

  def create
    @booking = Booking.new(rev_params)
    @garage = Garage.find(params[:garage_id])
    @client = current_user
    @booking.garage = @garage
    @booking.client = @client
    authorize @booking
    if @booking.save
      flash[:notice] = 'Ya tomamos tu reserva'
      redirect_to garage_path(@garage)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @booking.update(rev_params)
      flash[:notice] = 'Booking editado'
      redirect_to garage_path(@booking.garage)
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy
    redirect_to garage_path(@booking.garage)
  end

  def accept_booking
    @booking.status = 'confirmed'
    @booking.save
    redirect_to bookings_path
  end

  def decline_booking
    @booking.status = 'declined'
    @booking.save
    redirect_to bookings_path
  end

  private

  def rev_params
    params.require(:booking).permit(:initial_date, :end_date)
  end

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end
end

app/controllers/garages_controller.rb
class GaragesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :find_garage, only: %i[show edit destroy update]

  def index
    @garages = policy_scope(Garage).order(created_at: :desc)
    if params[:query].present?
      @garages = Garage.search_by_title_and_description(params[:query])
    else
      @garages = Garage.all
    end
  end

  def show
    @marker = [{
                lat: @garage.latitude,
                lng: @garage.longitude
              }]
  end

  def new
    @garage = Garage.new
    authorize @garage
  end

  def create
    @garage = Garage.new(rev_params)
    @garage.owner = current_user
    authorize @garage
    if @garage.save
      flash[:notice] = 'Garage creado'
      redirect_to garages_path(anchor: "garage-#{@garage.id}")
    else
      render :new
    end
  end

  def edit; end

  def update
    if @garage.update(rev_params)
      flash[:notice] = 'Garage editado'
      redirect_to garage_path(@garage)
    else
      render :edit
    end
  end

  def destroy
    @garage.destroy
    redirect_to garages_path
  end

  def my_garages
    @garages = policy_scope(Garage).select do |garage|
      garage.owner == current_user
    end
  end

  private

  def rev_params
    params.require(:garage).permit(:location, :photo, :title, :price)
  end

  def find_garage
    @garage = Garage.find(params[:id])
    authorize @garage
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class='d-flex'>
  <h1>Edit Booking</h1>
  <p>Price <%= @booking.garage.price %></p>
</div>
<%= simple_form_for [ @garage, @booking ] do |f| %>
  <%= f.input :initial_date %>
  <%= f.input :end_date %>

  <%= f.submit "Submit Booking", class: "btn btn-primary" %>
<% end %>

app/views/bookings/index.html.erb
<head>
  <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
</head>
<div class="container">
  <div class="container" id="my_garage_bookings">
    <% if !current_user.garages.empty? %>
      <h1>Solicitudes</h1>
      <div class="row">
        <% if !@bookings_owner.empty? %>
          <% @bookings_owner.each do |booking| %>
            <% if booking.status == "standby" %>
            <div class="card m-3">
                  <div class="card-title mt-2 d-flex justify-content-between">
                    Garage: <%= booking.garage.title %>
                    <%= link_to "Ver", booking.garage, :class => 'btn btn-outline-secondary btn-sm' %>
                  </div>
                  <div class="card-text">
                    Desde: <%= booking.initial_date%>
                    <br>Hasta: <%= booking.end_date %>
                  </div>
                  <div class="card-footer d-flex">
                    <%= link_to "Aceptar solicitud", accept_path(:id => booking.id), :class => 'btn btn-success btn-sm' %>
                    <%= link_to "Rechazar solicitud", decline_path(:id => booking.id), :class => 'btn btn-danger btn-sm' %>
                  </div>
              </div>
              <% elsif booking.status == 'confirmed' %>
                <div class="card m-3">
                    <div class="card-title mt-2 d-flex justify-content-between">
                      Garage: <%= booking.garage.title %>
                      <%= link_to "Ver", booking.garage , :class => 'btn btn-outline-secondary btn-sm' %>
                    </div>
                    <div class="card-text">
                     Desde: <%= booking.initial_date%>
                    <br>Hasta: <%= booking.end_date %>
                    </div>
                    <div class="card-footer d-flex justify-content-between">
                      <%= "Booking has been confirmed" %>
                        <span class="fa fa-check"></span>
                    </div>
                </div>
              <% else %>
                <div class="card m-3">
                    <div class="card-title mt-2 d-flex justify-content-between">
                      Garage: <%= booking.garage.title %>
                      <%= link_to "Ver", booking.garage, :class => 'btn btn-outline-secondary btn-sm' %>
                    </div>
                    <div class="card-text">
                    Desde: <%= booking.initial_date%>
                    <br>Hasta: <%= booking.end_date %>
                    </div>
                    <div class="card-footer d-flex justify-content-between">
                      <%= "Booking has been canceled" %>
                      <span class="fa fa-window-close"></span>
                    </div>
                </div>
            <% end %>
          <% end %>
          <% else %>
          <%= "No tenes solicitudes de booking todavía" %>
        <% end %>
    <% end %>
    </div>
  </div>
  <div class="container" id="my_client_bookings">
    <h1>Mis bookings</h1>
    <div class="row">
      <% if !@bookings_client.empty? %>
          <% @bookings_client.each do |booking| %>
            <div class="card m-3">
              <div class="card-title mt-2 d-flex justify-content-between">
                Garage: <%= booking.garage.title %>
                <%= link_to "Ver", booking.garage , :class => 'btn btn-outline-secondary btn-sm' %>
              </div>
              <div class="card-text">
                Desde: <%= booking.initial_date%>
                <br>Hasta: <%= booking.end_date %>
              </div>
              <div class="card-footer d-flex justify-content-between">
                <% if booking.status == "standby" %>
                    <p class="pending mt-3"><%= "Pending.." %> </p>
                    <%= link_to "Editar booking", edit_booking_path(booking), :class => 'btn btn-outline-dark' %>
                  <% elsif booking.status == 'confirmed'%>
                    <p class="confirmed mt-3"><%= "Confirmed" %> </p>
                  <% else %>
                    <p class="declined mt-3"><%= "Declined" %> </p>
                    <%= link_to "Elegir fechas", edit_booking_path(booking), :class => 'btn btn-outline-dark' %>
                <% end %>
              </div>
            </div>
          <% end %>
        <% else %>
        <div class="container">
          <%= "No tenes solicitudes de booking todavía" %>
        </div>
      <% end %>
    </div>
  </div>

</div>




<% #con respecto a los bookings_client %>

<% #standby %>
<% #standby
#confirmed
#declined %>
<% # La path para editar un booking es : edit_booking_path(booking) %>
<% # La path para eliminar un booking es : booking_path(booking), method: :delete, data: { confirm: "Are you sure?" }%>

app/views/bookings/new.html.erb
<div class="container">
    <h1>New Booking</h1>
    <div class="d-flex justify-content-end">
      <p class=“font-weight-bold”>Price: $<%= @garage.price %></p>
    </div>
  <div class="m-3">
    <%= simple_form_for [ @garage, @booking ] do |f| %>
      <%= f.input :initial_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.submit "Submit Booking", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/garages/edit.html.erb
<div class="container mt-4">
    <div class="row d-flex justify-content-center">
      <div class="col-6">
        <div class="garage-form">
          <h1>Edita tu garage</h1>
          <div class="mt-3">
            <%= simple_form_for @garage do |f| %>
            <%= f.input :title %>
            <%= f.input :price %>
            <%= f.input :location %>
            <%= f.input :photo, as: :file %>
            <div class="d-flex justify-content-center">
              <%= f.submit "Edit Booking", class: 'btn btn-primary' %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/garages/index.html.erb
<div class=“banner-content”>
  <div class="container">
    <h1 class="text-center">Compartí tu garage y ganemos todos</h1>
  </div>
  <div class="container d-flex justify-content-end">
    <%= form_tag garages_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Buscá garages"
      %>
      <%= submit_tag "", class: "btn btn-indigo btn-rounded btn-sm my-0 waves-effect waves-light" %>
    <% end %>
  </div>
  <div class="d-flex justify-content-center">
      <%= link_to "Creá tu garage!", new_garage_path, :class => 'btn btn-outline-secondary' %>
  </div>
</div>

<div class = "container cards">
  <div class="row">
    <% @garages.each do |garage| %>
      <div class=“col-sm-3”>
        <div class=card-deck>
          <div class="d-inline justify-content-center tarjeta" id="garage-<%=garage.id%>">
            <%= link_to garage_path(garage) do %>
              <div class="card shadow-sm pt-3 ">
              <div class="card-img-top">
                <% if garage.photo.attached? %>
                  <%= cl_image_tag(garage.photo.key,  height: 200, width: 300, crop: :fill) %>
                <% end %>
              </div>
                <div class="card-body">
                  <div class="d-flex justify-content-between">
                    <h4 class="card-title"><%= garage.title %></h4>
                    <p class="card-text">
                      En: <%= garage.location %>
                    </p>
                    <% if policy(garage).show? %>
                      <%= link_to "Ver garage", garage_path(garage), :class => 'btn btn-outline-dark btn-sm boton' %>
                    <% end %>
                  </div>
                  </div>
                  <div class="card-footer">
                    <div class="d-flex justify-content-around">
                      <div>$<%= garage.price %>/hs</div>
                      <div>Dueño: <%= garage.owner.full_name %></div>
                      <br>
                    </div>
                    <small class="author d-flex justify-content-end">Submitted <%= time_ago_in_words(garage.created_at) %> ago</small>
                </div>
              </div> <!-- aca termina el card -->

            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/garages/my_garages.html.erb
<h1>My garages</h1>
<div class = “container”>
  <div class="row">
    <% @garages.each do |garage| %>
      <div class=“col-sm-3”>
        <div class=card-deck>
          <div class="d-inline">
            <%= link_to garage_path(garage) do %>

              <div class="card shadow-sm" style="width: 432px; height:450px;">
              <div class="card-img-top">
                <% if garage.photo.attached? %>
                  <%= cl_image_tag(garage.photo.key,  height: 200, width: 400, crop: :fill) %>
                <% end %>
              </div>
                <div class="card-body">
                  <h4 class="card-title"><%= garage.title %></h4>
                  <p class="card-text">
                    Ubicación: <%= garage.location %>
                  </p>
                  <div class= "buttons d-flex justify-content-center">
                    <% if policy(garage).show? %>
                      <%= link_to "Ver", garage_path(garage), :class => 'btn btn-outline-dark' %>
                    <% end %>
                    <% if policy(garage).edit? %>
                      <%= link_to "Editar", edit_garage_path(garage), :class => 'btn btn-outline-dark' %>
                    <% end %>
                    <% if policy(garage).destroy? %>
                      <%= link_to "Eliminar", garage_path(garage), method: :delete, data: { confirm: "Are you sure?" }, :class => 'btn btn-outline-dark' %>
                    <% end %>
                  </div>
                  </div>
                  <div class="card-footer">
                    <div class="d-flex justify-content-around">
                      <div>Precio: $<%= garage.price %></div>
                      <div>Dueño: <%= garage.owner.full_name %></div>

                  </div>
                </div>
              </div> <!-- aca termina el card -->

            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/garages/new.html.erb
  <div class="container mt-4">
    <div class="row d-flex justify-content-center">
      <div class="col-6">
        <div class="garage-form">
          <h1>Creá tu garage</h1>
          <div class="mt-3">
            <%= simple_form_for @garage, remote: true do |f| %>
            <%= f.input :title %>
            <%= f.input :price %>
            <%= f.input :location %>
            <%= f.input :photo, as: :file %>
            <div class="d-flex justify-content-center">
              <%= f.submit "Submit Booking", class: 'btn btn-primary' %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/garages/show.html.erb
<br><br>
<div class="container">
  <div class="row d-flex">
    <div class="col-8">
      <div class="card shadow-sm pt-3 d-flex jusftify-content-center" style="width: 832px; ">
        <div class="card-img-top">
        <% if @garage.photo.attached? %>
          <%= cl_image_tag(@garage.photo.key,
          width: 800, height: 400, crop: :fill) %>
        <% end %>
        </div>
        <div class="card-body">
          <h3><%= @garage.title %></h3>
          <div class="d-flex justify-content-between">
            <p class="card-text">
              En: <%= @garage.location %>
            </p>
            <h4>$<%= @garage.price %>/hs</h4>
          </div>
          <div>
            <% if @garage.owner == current_user %>
              <%= link_to "Editar garage", edit_garage_path(@garage), :class => 'btn btn-outline-dark' %>
              <%= link_to "Eliminar garage", garage_path(@garage), method: :delete, data: { confirm: "Are you sure?" }, :class => 'btn btn-outline-dark' %>
            <% elsif user_signed_in? %>
              <% @bookings = @garage.bookings.select { |booking| current_user.bookings.include?(booking) } %>
              <% if @bookings != [] %>
                <p><%= link_to "Reservar otra fecha", new_garage_booking_path(@garage), class: "btn btn-primary" %>Ya tienes una reserva!</p>
              <% else %>
              <%= link_to "Reservar", new_garage_booking_path(@garage), class: "btn btn-outline-secondary btn-lg" %>
              <% end %>
            <% else %>
              <%= link_to "Sign Up to Make a Reservation", new_user_registration_path, :class => 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-3">
        <div class="card shadow-sm map" style="width: 300px; height:365px;">
          <div class="card-img-top">
            <div style="width: 300px; height: 300px;"
              data-controller="mapbox"
              data-mapbox-markers-value="<%= @marker.to_json %>"
              data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
            </div>
        </div>
        <div class="card-footer">
          <%= @garage.location %>
        </div>
      </div>

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Garagebnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <p class='notice'><%= notice %></p>
    <p class='alert'><%= alert %></p>
    <%= render 'shared/flashes' %>
    <% if params[:action] != 'home' %>
      <%= render "shared/navbar" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<body class=bk-image>
  <div class=sign-up>
    <%= link_to "Sign up", new_user_registration_path, :class => 'btn btn-success', style:"color: white;" %>
  </div>
    <div class=cont>
      <div style="text-align:center">
        <div class="banner text-align-center justify-content-center">
          <h2 class='subtitulo', style="color:white">Do you wanna park your car? You're in the right platform!</h2>
          <br><br>
          <h1 class='titulo', style="color:white; font-weight:bold;">GarageBNB</h1>
      </div>
      <div class=button>
        <%= link_to "Watch some garages", garages_path, :class => "btn btn-success btn-lg", style:"color: white;" %>
      </div>
    </div>
    </div>
</body>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon img-back ">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "icon.jpg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          </li>
          <li class="nav-item active">
            <%= link_to "Home", garages_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My garages", my_garages_path, class: "dropdown-item" %>
              <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>